apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 374445650484.dkr.ecr.us-east-1.amazonaws.com/frontend-test-app:latest
          envFrom:
            - configMapRef:
                name: frontend-config
          ports:
            - containerPort: 80
